test: isPalindrome
	./isPalindrome ""
	./isPalindrome "a"
	./isPalindrome "ab"
	./isPalindrome
	./isPalindrome foo bar
	./isPalindrome "A man, a plan, a canal, panama."

isPalindrome:
	g++ isPalindrome.cpp -o isPalindrome

clean:
	rm -f isPalindrome